modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/IberiaRediscovered/issues"
license="MIT"

[[mods]]
    modId="iberia_rediscovered"
    version="${version}"
    displayName="Iberia:Rediscovered"
    authors="SkySom"
    description='''
    '''

[[dependencies.iberia_rediscovered]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"