modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/IberiaRediscovered/issues"
license="MIT"

[[mods]]
    modId="iberia_rediscovered"
    version="${file.jarVersion}"
    displayName="Iberia:Rediscovered"
    authors="DivineAspect, SkySom"
    description='''
    '''

[[dependencies.iberia_rediscovered]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.0,)"
    ordering="NONE"
    side="BOTH"